### ISSUE TITLE
BackgroundTimer Scope?

### ISSUE THREAD

**Issue by ys27** [ocetnik/react-native-background-timer#1]
I have 
BackgroundTimer.start(5000);
DeviceEventEmitter.addListener('backgroundTimer', () => {
	this._startDailyTimer();
});
inside ComponentDidMount(), but I get an error saying:
Possible Unhandled Promise Rejection (id: 0): undefined is not an object.

Do these BackgroundTimer functions have to be used in the global scope, or am I doing something else wrong here?

Thank you.

**Comment by ocetnik** [comment]
I tried to test it now and everything is working properly in my case. Have you already solved this problem? If not, could you paste here any major piece of code and write on which line the error occurs?

**Comment by ys27** [comment]
So inside this one component.js, I have set 
`import BackgroundTimer from 'react-native-background-timer';`
Then inside the class, I have these two functions
```
 _startDailyTimer() {
        BackgroundTimer.stop();
        this._reduceAutoItems();
        //86400000
        BackgroundTimer.start(3000);
        DeviceEventEmitter.addListener('backgroundTimer', () => {
		this._reduceAutoItems();
	});
}
_startOffsetTimer() {
	AsyncStorage.getItem("Timer").then((value) => {
		if (value === null || value === false) {
			let now = new Date();
			let offset = moment().endOf('day')-now;
			BackgroundTimer.start(offset);
			DeviceEventEmitter.addListener('backgroundTimer', () => {
				this._startDailyTimer();
			});
			AsyncStorage.setItem("Timer", true);
		}
        });
}
```

Thank you.

**Comment by ocetnik** [comment]
The error is probably caused by adding boolean as the second parameter in `AsyncStorage.setItem("Timer", true);`
The second parameter (value) must be a **string**
Check https://facebook.github.io/react-native/docs/asyncstorage.html

**Comment by ys27** [comment]
I've changed the values into a string but the error persists.

**Comment by ys27** [comment]
Is it okay for there to be multiple instances of backgroundtimer? How does the string backgroundTimer as the first param in
```
DeviceEventEmitter.addListener('backgroundTimer', () => {
	this._reduceAutoItems();
});
```
relate to anything?

**Comment by IjzerenHein** [comment]
Did you link the library using `react-native link react-native-background-timer` ?

**Comment by ys27** [comment]
Yes, I have. Since then I have resorted to using modules to communicate with the android native components. Should I close this thread?

**Comment by ocetnik** [comment]
If everything is OK, you can.
