### ISSUE TITLE
 Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'

### ISSUE THREAD

**Issue by Shhzdmrz** [ocetnik/react-native-background-timer#105]
Constantly getting this warning on version **2.1.0-alpha.6.**

> WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
> It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Any plan to remove this before end of the year?

**Comment by ocetnik** [comment]
Fixed in #107
