### ISSUE TITLE
  BackgroundTimer.stopBackgroundTimer(); not working globally

### ISSUE THREAD

**Issue by wdayanand** [ocetnik/react-native-background-timer#106]
I started timer with  **BackgroundTimer.runBackgroundTimer** and close the app, timer working fine in background but when I restart application and app came to foreground I want to stop that timer so I tried with  **BackgroundTimer.runBackgroundTimer** but its not working

Please let me know how can I stop that timer or let me know how I will know the timer is already running in background

I used  "react-native-background-timer": "2.1.0-alpha.6",

**Comment by Prussich** [comment]
Just fix in the source code index.js

In function stopBackgroundTimer() replace: clearTimeout(this.backgroundTimer); to this.clearTimeout(this.backgroundTimer);

it worked for me. Tested in iOS. Not in Android. Author please correct the code.

**Comment by Solitaryo** [comment]
Having the same problem, and @Prussich is right

**Comment by ocetnik** [comment]
@wdayanand @Prussich @Solitaryo fixed in `react-native-background-timer@2.1.1`
