### ISSUE TITLE
Execution failed for task ':react-native-background-timer:verifyReleaseResources' - while assembling for Release. Backgroundtimer doesn't get executed while app in on background.

### ISSUE THREAD

**Issue by AshwinTayson** [ocetnik/react-native-background-timer#108]
My problem is twofold.

1. In debug version - Building works propely but not executed when app is on background but only when it is on foreground.

2. In release version - While building it throws the following error.

> /home/impact/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/b0014319950794f5c3e0a3fe67d28ce3/res/values-v26/values-v26.xml:9:5-12:13: AAPT: resource android:attr/colorError not found.
>     
> /home/impact/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/b0014319950794f5c3e0a3fe67d28ce3/res/values-v26/values-v26.xml:13:5-16:13: AAPT: resource android:attr/colorError not found.
>     
> /home/impact/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/b0014319950794f5c3e0a3fe67d28ce3/res/values-v26/values-v26.xml:17:5-93: AAPT: style attribute 'android:attr/keyboardNavigationCluster' not found.
>     
> /home/impact/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/b0014319950794f5c3e0a3fe67d28ce3/res/values/values.xml:251:5-69: AAPT: resource android:attr/fontStyle not found.
>     
> /home/impact/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/b0014319950794f5c3e0a3fe67d28ce3/res/values/values.xml:251:5-69: AAPT: resource android:attr/font not found.
>     
> /home/impact/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/b0014319950794f5c3e0a3fe67d28ce3/res/values/values.xml:251:5-69: AAPT: resource android:attr/fontWeight not found.
>     
> error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
> error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
> /home/impact/portfolio/employee-tracker/node_modules/react-native-background-timer/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:7: error: resource android:attr/colorError not found.
> /home/impact/portfolio/employee-tracker/node_modules/react-native-background-timer/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:11: error: resource android:attr/colorError not found.
> /home/impact/portfolio/employee-tracker/node_modules/react-native-background-timer/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
> /home/impact/portfolio/employee-tracker/node_modules/react-native-background-timer/android/build/intermediates/res/merged/release/values/values.xml:226: error: resource android:attr/fontStyle not found.
> /home/impact/portfolio/employee-tracker/node_modules/react-native-background-timer/android/build/intermediates/res/merged/release/values/values.xml:226: error: resource android:attr/font not found.
> /home/impact/portfolio/employee-tracker/node_modules/react-native-background-timer/android/build/intermediates/res/merged/release/values/values.xml:226: error: resource android:attr/fontWeight not found.
> error: failed linking references.
> 
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-background-timer:verifyReleaseResources'.
> > com.android.ide.common.process.ProcessException: Failed to execute aapt
> 

Step I've Tried.

Running the command `react-native link`

I've changed the android/app/build.gradle accordingly

**Comment by ArthurKnoep** [comment]
I am currently experiencing the same problem

**Comment by saveliy-kremen** [comment]
try add in android\build.gradle:

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 27
                buildToolsVersion '27.0.3'
            }
        }
    }
}

**Comment by LouisLeung** [comment]
same problem

**Comment by todeng** [comment]
Installing 2.1.0-alpha.7 version resolved the issue

`npm i --save react-native-background-timer@2.1.0-alpha.7`

**Comment by ocetnik** [comment]
@AshwinTayson @ArthurKnoep @saveliy-kremen @LouisLeung @todeng fixed in `react-native-background-timer@2.1.1`

**Comment by mjm918** [comment]
This problem is back... I am using `2.1.1`

**Comment by kimho** [comment]
same problem

**Comment by keremcubuk** [comment]
I have the same issue at the latest version `v2.1.1 and others`. Any solution?

**Comment by ithustle** [comment]
+1

**Comment by Maxdevelopsffs** [comment]
Hello guys, I solve my problem with the following command:
./gradlew app: assembleRelease

notice that I have an app.

:)
