### ISSUE TITLE
Android wakelock and battery consumption

### ISSUE THREAD

**Issue by peacechen** [ocetnik/react-native-background-timer#109]
How much does holding a wakelock affect battery life on Android?  It looks like it's held for the life of the app, not released until `onHostDestroy`:
https://github.com/ocetnik/react-native-background-timer/blob/6d7b0a02aadfeb7745eafdf7336a1bd4d664766d/android/src/main/java/com/ocetnik/timer/BackgroundTimerModule.java#L24

Would it be more power efficient to acquire the wakelock on `start` and release it on `stop` ?

**Comment by roysG** [comment]
Yes, same issue for me, i close the app (not minimize it) but the wakelock is still on.
I also check how much time the app awake the phone and it was for 8h!.

Please tell us how can we disable / release the wakelock.

**Comment by ocetnik** [comment]
Fixed in #126 

@peacechen @roysG please try update to `react-native-background-timer@2.2.0-alpha.0` and let me know if everything works well.

Thanks a lot.

**Comment by peacechen** [comment]
Thanks @ocetnik for fixing this important issue.  It works great.
