### ISSUE TITLE
Timer unable to stop on iOS

### ISSUE THREAD

**Issue by isaaclem** [ocetnik/react-native-background-timer#111]
```
let i = 0;
BackgroundTimer.runBackgroundTimer(() => { 
  i++;
  console.log('DEBUG::i', i);
}, 1000);
```

`"react-native-background-timer": "2.1.0-alpha.5"`

Based on your comment [https://github.com/ocetnik/react-native-background-timer/issues/86#issuecomment-414957431](url), I've upgraded to this specific version and it does working perfectly where it able to console log when iOS app in background.

The problem now is that it doesn't seems to be able to stop with `BackgroundTimer.stopBackgroundTimer();`

**Comment by isaaclem** [comment]
Just to be clear that I've also tried the `Usage iOS` way as below
```
    BackgroundTimer.start();
    let i = 0;
    this.interval = setInterval(() => {
      i++;
      console.log('DEBUG::i', i);
    }, 1000);
```
```
BackgroundTimer.stop();
```

The above way is worse as it will stop running once the app being minimized.

**Comment by isaaclem** [comment]
Just noticed in your recent commit where the version is now 2.1.1...It's working fine now in iOS. Thank you very much!

**Comment by poonamnimse** [comment]
Hi @isaaclem, how you have resolve this issue because i am also having version 2.1.1, but in my case when application is minimised timer also get paused.Can you please share your implementation or setting?

**Comment by smile1130** [comment]
I am looking forward to this solution now.

Thanks in advance
