### ISSUE TITLE
Cannot read property 'setTimeout' of undefined

### ISSUE THREAD

**Issue by PL-SQL** [ocetnik/react-native-background-timer#114]

**Comment by smitthakkar1** [comment]
same issue ? any work around ?

**Comment by ocetnik** [comment]
Hey @smitthakkar1! I updated the installation section in the readme. If you use [Expo](https://expo.io/) to create a project [you'll just need to](https://facebook.github.io/react-native/docs/getting-started#caveats) "[eject](https://docs.expo.io/versions/latest/expokit/eject)". And you also need to link the library.
