### ISSUE TITLE
Calling functions

### ISSUE THREAD

**Issue by RailtonMatthew** [ocetnik/react-native-background-timer#12]
Hi, how do I call one of my functions from the timer.  For example, in index.android.js

import BackgroundTimer from 'react-native-background-timer';
const intervalId = BackgroundTimer.setInterval(() => {
    console.log('tic 1'); // This displays ok.
    this.tick(); // This gives undefined is not an object (evaluating '_this.tick')
    }, 3000);

class Test extends Component {

  tick() {
    console.log('tic 2');
  }

}

Thanks

**Comment by ocetnik** [comment]
Hi, please try this:

```javascript
import React, { Component } from 'react';
import {
  AppRegistry,
  Text,
  View,
} from 'react-native';

import BackgroundTimer from 'react-native-background-timer';

class TimerTest extends Component {

  componentWillMount() {
    const intervalId = BackgroundTimer.setInterval(() => {
      console.log('tic 1');
      this.tick();
    }, 3000);
  }

  tick() {
    console.log('tic 2');
  }

  render() {
    return (
      <View>
        <Text>
          Hello World!
        </Text>
      </View>
    );
  }
}

AppRegistry.registerComponent('TimerTest', () => TimerTest);
```

**Comment by RailtonMatthew** [comment]
Hi, thanks for the reply.  This now see's the function but when the app is in the background I get the following error in the console:

Can't find variable: intervalId

**Comment by ocetnik** [comment]
Can you paste here your whole code, please?

**Comment by RailtonMatthew** [comment]
I created a new project with the example that you gave and it is working Ok.  I think there must be something in my main project that is failing/crashing when it goes into background and this is causing the error.

Thanks for your help. :)
