### ISSUE TITLE
Clearing timer

### ISSUE THREAD

**Issue by RailtonMatthew** [ocetnik/react-native-background-timer#14]
Hi, I'm using the timer on Android and it's working great.  However, I am unable to shut it down cleanly when exiting the app.  I tried the following code but the function never gets called.  Any ideas?

Thanks.

```
componentWillUnmount() {
    console.log('unmount');
    BackgroundTimer.clearInterval(intervalId);
}

```

**Comment by kesjien** [comment]
You should use this, this.intervalId - create timer, clearInterval(this.intervalId)

**Comment by RailtonMatthew** [comment]
Thanks for the reply.  My problem is that the componetWillUnmount function does not get executed when the app closes so it never tries to clear intervalId

**Comment by ocetnik** [comment]
Hi @RailtonMatthew,

you should use [AppState API](https://facebook.github.io/react-native/docs/appstate.html) for app state detection.

**Comment by RailtonMatthew** [comment]
Sorry, but how does this help?  AppState indicates active, inactive or background, not when the app exits.

**Comment by ocetnik** [comment]
When app is closing, the state is not changed to inactive?

So, please try add componentWillUnmount into your **root** component (the same approach is used in [example](https://facebook.github.io/react-native/docs/appstate.html#basic-usage) where event listener is removed)
