### ISSUE TITLE
[Android] Stop working when phone is locked

### ISSUE THREAD

**Issue by Rewieer** [ocetnik/react-native-background-timer#15]
It seems it's also the case on IOS (see #9 ) and now I just tested it on Android and it's not working when the phone is locked.

**Comment by Rewieer** [comment]
I found a quick fix for it. Is this still maintained @ocetnik  ? I might PR.

**Comment by ocetnik** [comment]
Hi @Rewieer, thank you for your observation.

@ericacooksey fixed it in #17 but on my devices everything worked well also with previous version (0.1.3).

I just released 0.1.4-beta so please try `npm i react-native-background-timer@beta --save` and let me know if it works properly when phone is locked.

Many thanks.

**Comment by Rewieer** [comment]
I'm sorry, I cannot try your solution for now as I've finally implemented my own background-timer system. If it's necessary i will try it out.
I want to point that using sony phones, when stamina mode is on (or what the setting to disallow applications to fetch datas while in sleep mode) disable using a background timer. I've been tricked for the whole week-end on this. You should maybe talk about it in the README to avoid further problems on these phones.

**Comment by Rewieer** [comment]
@MaximilianKindshofer do you want me to share the solution ? It requires a bit of knowledge in Java to implement through

**Comment by MaximilianKindshofer** [comment]
This would be great!
I am not so skilled at Java - but I am sure I can dive into it

**Comment by Rewieer** [comment]
It's pretty minimal for my purpose.
The module looks like this : 

    
    import android.os.Handler;
    import android.os.PowerManager;
    
    import com.facebook.react.bridge.ReactApplicationContext;
    import com.facebook.react.bridge.ReactContextBaseJavaModule;
    import com.facebook.react.bridge.ReactMethod;
    import com.facebook.react.modules.core.DeviceEventManagerModule;
    
    import static android.content.Context.POWER_SERVICE;
    
    public class BackgroundTimerModule extends ReactContextBaseJavaModule {
      private PowerManager powerManager;
      private PowerManager.WakeLock wakeLock;
    
      public BackgroundTimerModule(ReactApplicationContext reactContext){
        super(reactContext);
    
        this.powerManager = (PowerManager) getReactApplicationContext().getSystemService(POWER_SERVICE);
        this.wakeLock = powerManager.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK, "rewieer_bg_wakelock");
        this.wakeLock.acquire();
      }
    
      @Override
      public String getName() {
        return "RewieerBackgroundTimerModule";
      }
    
      @ReactMethod
      public void setTimeout(final int id, final int timeout){
        Handler handler = new Handler();
        handler.postDelayed(new Runnable() {
          @Override
          public void run() {
            if(getReactApplicationContext().hasActiveCatalystInstance()){
              getReactApplicationContext()
                  .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                  .emit("rewieer.backgroundTimer.timeout", id);
            }
          }
        }, timeout);
    
      }
    }

It basically acquire a partial wakelock permanently to ensure CPU is not sleeping.
Then in JS : 

    import { NativeModules, DeviceEventEmitter } from 'react-native';
    
    const NativeEVOBackgroundTimer = NativeModules.RewieerBackgroundTimerModule;
    
    const listeners = {};
    let uniqueId = 0;
    
    const nextId = () => uniqueId++;
    
    const RewieerBackgroundTimer = {
      setInterval(callback, delay){
    
        let id = nextId();
        listeners[id] = {
          isInterval: true,
          callback,
          timeout: delay,
        };
    
        NativeEVOBackgroundTimer.setTimeout(id, delay);
        return id;
      },
      clearInterval(id){
        listeners[id] && delete listeners[id];
      }
    };
    
    DeviceEventEmitter.addListener("rewieer.backgroundTimer.timeout", (id) => {
      const listener = listeners[id];
      if(!listener){
        return;
      }
    
      listener.callback();
      if(listener.isInterval){
        NativeEVOBackgroundTimer.setTimeout(id, listener.timeout);
        return;
      }
    
      delete listeners[id];
    });
    
    export default RewieerBackgroundTimer;

The interface is the same as RNBT but it doesn't provide any setTimeout function, because I don't need it. You can implement it easily through, just copy the code of RNBT. 
If you have no idea on how to implement this head to [the react native doc](https://facebook.github.io/react-native/docs/native-modules-android.html).

**Don't forget to add `<uses-permission android:name="android.permission.WAKE_LOCK" />` to your manifest.**

This solution can certainly be discussed and improved, as it drains the battery life when used heavily.

**Comment by MaximilianKindshofer** [comment]
Yes I can see that this will be really battery heavy - meanwhile I found: 
https://github.com/vikeri/react-native-background-job
Utilizing the https://developer.android.com/reference/android/app/job/JobScheduler.html

But this wont work in foreground

**Comment by Rewieer** [comment]
You might actually implement an interface and switch given the context.
For my project I have a BaseComponent React Element. If the app is in background, it renders BackgroundComponent. If the app is in foreground, it renders ForegroundComponent. Each use different kind of periodic methods.

**Comment by Rewieer** [comment]
For my work I need to do repetitive task every 30 seconds. I've looked at JobSchedulers but it's more like a way to synchronize your application. I don't think your setInterval method has an interval of 15 minutes :p

**Comment by irekrog** [comment]
@ocetnik Is a chance to resolve this problem? 
I have noticed too when app is running by react-native run-android a timer still working even when phone is locked. But when app has been installed by .apk file then timer is stopped after 30-40 seconds.

**Comment by Rewieer** [comment]
@irekrog there might be many causes to this and I must admit i'm as well struggling with such problems.
If the timer stop workings when phone is locked, it's a Wakelock problem.

**Comment by ocetnik** [comment]
#9

**Comment by ocetnik** [comment]
#

**Comment by chenyi5266** [comment]
rn can't run task on background, it can be killed when CPU dormancy, I use Android native run background task and emit event to rn listener ..... 
[https://facebook.github.io/react-native/docs/native-modules-android.html](url)

**Comment by Rewieer** [comment]
Well RN is perfectly capable of doing this with a bit of native code, at least under android. That's what HeadlessJS do. A wakelock is sufficient to keep the CPU awake for background tasks, but it's resource consuming.
If it's about fetching notification like every hour or so, AlarmManager fits perfectly.

**Comment by sindhu732** [comment]
Issue still present on Android. Is there a solution?

**Comment by rohitshampur** [comment]
hey @sindhu732 i have added the solution given by @Rewieer , check this [Link](https://github.com/rohitshampur/react-native-background-timer/commit/a1a94f68e9865b22247edbf43171dabc530c6ea7)

**Comment by GhayoorUlHaq** [comment]
> It's pretty minimal for my purpose.
> The module looks like this :
> 
> ```
> import android.os.Handler;
> import android.os.PowerManager;
> 
> import com.facebook.react.bridge.ReactApplicationContext;
> import com.facebook.react.bridge.ReactContextBaseJavaModule;
> import com.facebook.react.bridge.ReactMethod;
> import com.facebook.react.modules.core.DeviceEventManagerModule;
> 
> import static android.content.Context.POWER_SERVICE;
> 
> public class BackgroundTimerModule extends ReactContextBaseJavaModule {
>   private PowerManager powerManager;
>   private PowerManager.WakeLock wakeLock;
> 
>   public BackgroundTimerModule(ReactApplicationContext reactContext){
>     super(reactContext);
> 
>     this.powerManager = (PowerManager) getReactApplicationContext().getSystemService(POWER_SERVICE);
>     this.wakeLock = powerManager.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK, "rewieer_bg_wakelock");
>     this.wakeLock.acquire();
>   }
> 
>   @Override
>   public String getName() {
>     return "RewieerBackgroundTimerModule";
>   }
> 
>   @ReactMethod
>   public void setTimeout(final int id, final int timeout){
>     Handler handler = new Handler();
>     handler.postDelayed(new Runnable() {
>       @Override
>       public void run() {
>         if(getReactApplicationContext().hasActiveCatalystInstance()){
>           getReactApplicationContext()
>               .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
>               .emit("rewieer.backgroundTimer.timeout", id);
>         }
>       }
>     }, timeout);
> 
>   }
> }
> ```
> 
> It basically acquire a partial wakelock permanently to ensure CPU is not sleeping.
> Then in JS :
> 
> ```
> import { NativeModules, DeviceEventEmitter } from 'react-native';
> 
> const NativeEVOBackgroundTimer = NativeModules.RewieerBackgroundTimerModule;
> 
> const listeners = {};
> let uniqueId = 0;
> 
> const nextId = () => uniqueId++;
> 
> const RewieerBackgroundTimer = {
>   setInterval(callback, delay){
> 
>     let id = nextId();
>     listeners[id] = {
>       isInterval: true,
>       callback,
>       timeout: delay,
>     };
> 
>     NativeEVOBackgroundTimer.setTimeout(id, delay);
>     return id;
>   },
>   clearInterval(id){
>     listeners[id] && delete listeners[id];
>   }
> };
> 
> DeviceEventEmitter.addListener("rewieer.backgroundTimer.timeout", (id) => {
>   const listener = listeners[id];
>   if(!listener){
>     return;
>   }
> 
>   listener.callback();
>   if(listener.isInterval){
>     NativeEVOBackgroundTimer.setTimeout(id, listener.timeout);
>     return;
>   }
> 
>   delete listeners[id];
> });
> 
> export default RewieerBackgroundTimer;
> ```
> 
> The interface is the same as RNBT but it doesn't provide any setTimeout function, because I don't need it. You can implement it easily through, just copy the code of RNBT.
> If you have no idea on how to implement this head to [the react native doc](https://facebook.github.io/react-native/docs/native-modules-android.html).
> 
> **Don't forget to add `<uses-permission android:name="android.permission.WAKE_LOCK" />` to your manifest.**
> 
> This solution can certainly be discussed and improved, as it drains the battery life when used heavily.

As you wrote setTimeOut, how can I implement SetTimeInterval in same way?

**Comment by rewieer** [comment]
@GhayoorUlHaq just call setTimeout again once the function times out.

**Comment by GhayoorUlHaq** [comment]
@rewieer  actually I have to execute a some lines of code after specific time period that will be defined by user and those lines should execute periodically even app is in background and phone is locked unless user stop that.
