### ISSUE TITLE
Crash on Simulator iOS 10 - Xcode 8 

### ISSUE THREAD

**Issue by MikaDo0211** [ocetnik/react-native-background-timer#16]
I installed react-native-background-timer with Ract-Native.
"react": "15.4.1",
"react-native": "0.39.1",
"react-native-background-timer": "^0.1.3",

1. Run it on simulator and error.
<img width="573" alt="screen shot 2016-12-09 at 00 22 16" src="https://cloud.githubusercontent.com/assets/1137725/21020145/c430bbd6-bda5-11e6-87df-24f56c111e38.png">

2. If I remove -ObjC
<img width="456" alt="screen shot 2016-12-09 at 00 22 42" src="https://cloud.githubusercontent.com/assets/1137725/21020148/cc220a02-bda5-11e6-9d93-d767639a7224.png">

App run and crash simulator.
<img width="599" alt="screen shot 2016-12-09 at 00 24 53" src="https://cloud.githubusercontent.com/assets/1137725/21020181/f0397f88-bda5-11e6-9be6-708f0baf5f1e.png">

How can I fix it? Please help me check. 

Thanks so much. @ocetnik

**Comment by manjeets12** [comment]
@MikaDo0211  how did you solved that plz mention your solution
