### ISSUE TITLE
Not Working in Xiaomi Redmi Note 7 - Android 9 MIUI 10.3.10

### ISSUE THREAD

**Issue by marcos93net** [ocetnik/react-native-background-timer#166]
Hello this does not work on my device Xiaomi Redmi Note 7 - Android 9. Could you help me? Do not display any errors in logcat. Already tested with another device and works normal. Just does not work on Xiaomi MIUI. Help me please.

**Comment by nestorgm** [comment]
Could it be related to this: https://www.freecodecamp.org/news/why-your-push-notifications-never-see-the-light-of-day-3fa297520793/
https://stackoverflow.com/questions/48166206/how-to-start-power-manager-of-all-android-manufactures-to-enable-background-and/48641229#48641229

**Comment by marcos93net** [comment]
> Could it be related to this: https://www.freecodecamp.org/news/why-your-push-notifications-never-see-the-light-of-day-3fa297520793/
> https://stackoverflow.com/questions/48166206/how-to-start-power-manager-of-all-android-manufactures-to-enable-background-and/48641229#48641229

How can I put these codes in my react native?

**Comment by Kranysys** [comment]
I have the same device (Redmi Note 7, Android 9, MIUI 10.3.6) and it's working very well. It's not a problem of device.
Make sure you have the right permissions (WAKE_LOCK, ....) in the Android Manifest and anywhere else.

**Comment by rmamtaventures** [comment]
I'm also facing the same issue.
