### ISSUE TITLE
Cannot read property 'setTimeout' line 48

### ISSUE THREAD

**Issue by anhtuank7c** [ocetnik/react-native-background-timer#20]
Hi,
I do implement `BackgroundTimer` in `componentDidMount`, but getting error in `node-modules/react-native-background-time/index.js` [line 48](https://github.com/ocetnik/react-native-background-timer/blob/master/index.js#L48)

RN: `0.40.0`
Please help take a look.

**Comment by ocetnik** [comment]
Hi @anhtuank7c,

Could you please paste here your code, your error log and Android/iOS version?

Thank you.

**Comment by anhtuank7c** [comment]
Hi,

I don't use this module anymore.
In my case, i follow your guide and then import BackgroundTimer, then use `BackgroundTimer.setInterval(() => console.log('bgTimer'), 1000)` in `componentDidMount`.

**Comment by jdpigeon** [comment]
I'm having this same error.

`undefined is not an object (evaluating `RNBackgroundTimer.setTimeout`)


03-15 13:23:30.135 15967-3663/com.neurodoro E/ReactNativeJS: undefined is not an object (evaluating 'RNBackgroundTimer.setTimeout')
03-15 13:23:30.281 15967-3663/com.neurodoro E/ReactNativeJS: undefined is not an object (evaluating 'this._component.getScrollableNode')`

**Comment by jdpigeon** [comment]
Got over this problem by running `react-native link react-native-background-timer`

I'm an idiot and didn't read the install directions completely...
