### ISSUE TITLE
Using react-native-background-timer inside saga

### ISSUE THREAD

**Issue by Ajmal0197** [ocetnik/react-native-background-timer#249]
How to use yield inside this library

            BackgroundTimer.runBackgroundTimer(() => {
                yield put({
                        type: types.FUSIONTIMER_PROJECT_ID,
                        payload: { heatingTimer: 'bg' }
                    })
            }, 1000);
        }

**Comment by shiroze** [comment]
you close the issues without solution ? @Ajmal0197

**Comment by Ajmal0197** [comment]
Passing 'dispatch' from component to saga in payload can be used in place of 'yield put'.
