### ISSUE TITLE
Installation failed. 

### ISSUE THREAD

**Issue by fozzarelo** [ocetnik/react-native-background-timer#25]
Got this error after installation/link:

ld: library not found for -lRCTActionSheet
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ocetnik** [comment]
Hi @fozzarelo,
I tested it right now with pure installation
```
brew install node
brew install watchman
npm install -g react-native-cli
react-native init AwesomeProject
cd AwesomeProject
npm i react-native-background-timer --save
react-native link
react-native run-ios
```
and everything works properly. Should you pase here full error log, please?

Thanks.
David

**Comment by fozzarelo** [comment]
Thank you @ocetnik. 
I should have closed the issue, as I managed to install a couple days ago. 
My prob was I had lRCTActionSheet twice and was causing conflicts. Once I removed it from your libs it ran fine. 
I ended up bailing on the repo :(. I do need true background functionality. 
I like the concept though, It would be a super simple solution for a number of situations. 
Good work man.
