### ISSUE TITLE
BackgroundTimer.stopBackgroundTimer(); not working

### ISSUE THREAD

**Issue by aashiriftikhar** [ocetnik/react-native-background-timer#257]
Hello everyone. I am using react-native-background-timer. And I wanted to perform a function for once only.
But the cross platform function BackgroundTimer.runBackgroundTimer() keeps executing the function after every interval. I tried stopping it from the function but it keeps executing the code. I dont know what I am doing wrong.
I dont want to use other functions as they are platform dependent. I wanted to use this function because it is cross platform.

Note: I wanted to run the function for once only.
My code;

`componentDidMount(){
    BackgroundTimer.runBackgroundTimer(() => {
      this.deleteAll()
    }, 18000);
}

deleteAll=()=>{
console.log('Deleted')
BackgroundTimer.stopBackgroundTimer();

}`
Any other cross platform approach for executing the function 'once' only will be appreciated. Thanks

Will be waiting for reply.

RN Version: 0.63.2
BG-Timer version: Latest package.

**Comment by koushikv04** [comment]
same here

**Comment by scrapecoder** [comment]
@aashiriftikhar you can use 

        // Start a timer that runs once after X milliseconds
        const timeoutId = BackgroundTimer.setTimeout(() => {
	   // this will be executed once after 10 seconds
	   // even when app is the the background
         console.log('tac');
         }, 10000);

      // Cancel the timeout if necessary 
      BackgroundTimer.clearTimeout(timeoutId);

**Comment by aashiriftikhar** [comment]
> @aashiriftikhar you can use
> 
> ```
>     // Start a timer that runs once after X milliseconds
>     const timeoutId = BackgroundTimer.setTimeout(() => {
>    // this will be executed once after 10 seconds
>    // even when app is the the background
>      console.log('tac');
>      }, 10000);
> 
>   // Cancel the timeout if necessary 
>   BackgroundTimer.clearTimeout(timeoutId);
> ```

I could use it, but setTimeout() func is platform dependent. It works on Android. I want for cross platform.

Btw, Thanks for you reply.

**Comment by scrapecoder** [comment]
@aashiriftikhar 

     import { DeviceEventEmitter, 
     NativeAppEventEmitter, Platform } from 'react- 
      native';
     import BackgroundTimer from 'react-native-background-timer';

    const EventEmitter = Platform.select({
    ios: () => NativeAppEventEmitter,
    android: () => DeviceEventEmitter,
     })();

      class BackgroundTimer {
       static setInterval(callback, delay) {
        BackgroundTimer.start();
        this.backgroundListener = 
         EventEmitter.addListener("backgroundTimer", () => {
           this.backgroundTimer = 
          BackgroundTimer.setInterval(callback, delay);
        });
        return this.backgroundListener;
    }

    static clearInterval(timer) {
        if (timer) timer.remove();
        if (this.backgroundTimer) BackgroundTimer.clearInterval(this.backgroundTimer);
        BackgroundTimer.stop();
      }
    }

      export default BackgroundTimer;  `

**Comment by aashiriftikhar** [comment]
> @aashiriftikhar
> 
> ```
>  import { DeviceEventEmitter, 
>  NativeAppEventEmitter, Platform } from 'react- 
>   native';
>  import BackgroundTimer from 'react-native-background-timer';
> 
> const EventEmitter = Platform.select({
> ios: () => NativeAppEventEmitter
> android: () => DeviceEventEmitter,
>  })();
> 
>   class BackgroundTimer {
>    static setTimeout(callback, delay) {
>     BackgroundTimer.start();
>     this.backgroundListener = 
>      EventEmitter.addListener("backgroundTimer", () => {
>        this.backgroundTimer = 
>       BackgroundTimer.setTimeout(callback, delay);
>     });
>     return this.backgroundListener;
> }
> 
> static clearTimeout(timer) {
>     if (timer) timer.remove();
>     if (this.backgroundTimer) BackgroundTimer.clearTimeout(this.backgroundTimer);
>     BackgroundTimer.stop();
>   }
> }
> 
>   export default BackgroundTimer
> ```
> 
> Try with this:
> 
> ```
>    const backgroundTimeout = BackgroundTimer.setTimeout(callback, 1000);
>    BackgroundTimer.clearTimeout(timer)
> ```

Thankyou so much sir ♥

**Comment by hengkx** [comment]
same issue
