### ISSUE TITLE
Can not read property setTimeout of undefined

### ISSUE THREAD

**Issue by parth19** [ocetnik/react-native-background-timer#32]
I've installed and imported the react-native-background-timer module.
I've added the code exactly as shown in your readme for setInterval or setTimeout, but I am getting "Can not read property setTimeout of undefined" error.

I am able to log the BakckgroundTimer Object value which is looking fine(Means it is not actually undefined). But whenever I try to call setTimeout or setInterval method it gives me error.

Do we need to do any other configuration apart from what is shown in readme.md?
If no, Can you help me figure out this issue?

**Comment by thethanghn** [comment]
you can use my fork temporarily to fix this problem @parth19

**Comment by parth19** [comment]
Ok, @thethanghn . I ran "react-native link" command. After that, I am getting below error while building the app.

CompileC /ios/build/Build/Intermediates/RNBackgroundTimer.build/Debug-iphonesimulator/RNBackgroundTimer.build/Objects-normal/x86_64/RNBackgroundTimer.o RNBackgroundTimer.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

Do I need to do anything specifically for IOS?

**Comment by thethanghn** [comment]
nope, my fork is only to fix that Android issue, nothing to do with iOS.

For that, try clean your project and rebuild

**Comment by parth19** [comment]
ok, no problem. Thanks for you time @thethanghn

**Comment by ocetnik** [comment]
Hi @parth19 and @thethanghn,

please let me know if version 1.0.3 works correctly.

Thanks.

**Comment by catgualter** [comment]
Hi, @ocetnik! Using version 1.0.3 and still getting the same error on Android.

**Comment by hyperh** [comment]
Getting a similar issue in v1.0.3. Do I need to do `pod install` before using this?

**Comment by ystrdy** [comment]
@thethanghn thx

**Comment by ocetnik** [comment]
@hyperh yes, you need to link the library. Check the installation section in the readme.
