### ISSUE TITLE
undefined is not an object (evaluating 'RNBackgroundTimer.setTimeout'

### ISSUE THREAD

**Issue by dadsteph** [ocetnik/react-native-background-timer#35]
I'm getting this error:

![simulator screen shot 28 jun 2017 16 33 57](https://user-images.githubusercontent.com/29259624/27661360-9c02648e-5c1f-11e7-8e00-5ed4e87bac71.png)

This is the source code:

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
} from 'react-native';


import BackgroundTimer from 'react-native-background-timer';

class WorkerSampleApp extends Component {


  render() {

    return (
      <View style={styles.container}>
        <TouchableOpacity onPress={() => {

          // Start a timer that runs once after X milliseconds
          const timeoutId = BackgroundTimer.setTimeout(() => {
          	// this will be executed once after 10 seconds
          	// even when app is the the background
            	console.log('tac');

          }, 10000);

          // Cancel the timeout if necessary
          BackgroundTimer.clearTimeout(timeoutId);
          
        }}>
          <Text style={styles.welcome}>
            Send message
          </Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});


AppRegistry.registerComponent('WorkerSampleApp', () => WorkerSampleApp);
```

Please help...

**Comment by prayasht** [comment]
Did you remember to run `react-native link` after installing the module?

**Comment by the-simian** [comment]
I wanted to share that the link command alone did not help me, in the long run I had to  link manually. In your `src/main/java/com/appname/MainApplication.java `

```java
import com.ocetnik.timer.BackgroundTimerPackage;

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new VectorIconsPackage(),
          //........and so on
          new BackgroundTimerPackage()
      );
    }

```

**Comment by JimSchofield** [comment]
I used `react-native link` and I checked `src/main/java/com/appname/MainApplication.java` for the correct links.  Still getting the same error here... What might be going on?

**Comment by the-simian** [comment]
another thing to check is in your `settings.gradle` located in the android root has the following entries as well:
````

include ':react-native-background-timer'
project(':react-native-background-timer').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-background-timer/android')

**Comment by JimSchofield** [comment]
@the-simian gradle entries were identical to what you supplied.  For some reason I re-imported it and tried using it and it worked... I wish I could tell you what I was doing wrong.  Thanks for the help!

**Comment by the-simian** [comment]
glad to hear its working for you :)

**Comment by ocetnik** [comment]
@dadsteph Did previous comments help you? Can I close this issue?

**Comment by KenilDomadia** [comment]
I am working with expo integrated app, the above steps couldn't solve the issue for me. Is there anything else I can do to solve the issue?

**Comment by pencilcheck** [comment]
Works for me after adding the lines in `MainApplication.java` in addition to the `react-native link`

**Comment by natterstefan** [comment]
@the-simian thanks for your [comment](https://github.com/ocetnik/react-native-background-timer/issues/35#issuecomment-312783840) it did work for me as well now. Wondering why this is not properly working or in the Readme.

**Comment by the-simian** [comment]
Right on @natterstefan ~! React Native... sometimes you gotta jiggle the cables you know?

**Comment by zorobabel** [comment]
@dadsteph Check this [comment](https://github.com/ocetnik/react-native-background-timer/issues/45#issuecomment-360983289)

@ocetnik I think you can close this issue

**Comment by akshayseth** [comment]
Not working on expo!

**Comment by ocetnik** [comment]
@akshayseth If you use Expo [you'll just need to](https://facebook.github.io/react-native/docs/getting-started#caveats) "[eject](https://docs.expo.io/versions/latest/expokit/eject)". Check the installation section in the readme.

**Comment by the-simian** [comment]
@akshayseth I'm using expo these days also, honestly, I often have problems when I stray from expo's ecosystem unless I eject (which I usually don't because there's a lot of downsides to that)

**Comment by zualas** [comment]
One more thing to the discussion: if you are using remote debugging via Wifi with a real phone, you still need to connect via cable. Remote reloading delivers only the Javascript files, while you need the new app build, which can only be delivered through a cable.

**Comment by haratmalli** [comment]
if you were just install this and testing with
`BackgroundTimer.runBackgroundTimer(() => { 
//code that will be called every 3 seconds 
}, 
3000);`
and got `null is not an object (evaluating 'RNBackgroundTimer.start')` error.
You should rebuild app like `react-native run-android`

**Comment by prajna-h** [comment]
Not working for me even after linking the module manually. Please help : (

**Comment by Nogias9x** [comment]
I'm also facing this problem although I already followed the README (manual linking included) :(
