### ISSUE TITLE
runBackgroundTimer doesn't work on RN 66.3  - Tested on Android

### ISSUE THREAD

**Issue by ZanaNabaz** [ocetnik/react-native-background-timer#399]
runBackgroundTimer() doesn't work on RN: "0.66.3". Does start the function, however it stops when screen is locked. Tested on Android.

**Comment by freekingg** [comment]
me too

**Comment by cemocanon** [comment]
same

**Comment by Simoon-F** [comment]
ios doesn't work either

**Comment by 27SageRO** [comment]
https://github.com/ocetnik/react-native-background-timer/issues/397#issuecomment-1230975865

**Comment by jamesdmurphy51** [comment]
Same issue with me.....using cross platform code

**Comment by ZanaNabaz** [comment]
I'm closing this issue since it's not beeing looked intro.

I replaced the logic in my app that requires the background task, I used a backend api for the task and then I'm pushing a notification to the device with the information I needed. Look intro silent notification if you guys plan on doing the same.
