### ISSUE TITLE
Cannot read property 'setTimeout' of undefined

### ISSUE THREAD

**Issue by cideM** [ocetnik/react-native-background-timer#40]
Steps that cause the error: 
* Create app with `create-react-native-app`
* `yarn add react-native-background-timer`
* `react-native link`
* `yarn start`

Code that leads to the issue:
```
  startFetching() {
    console.log("start fetching")

    const timerId = BackgroundTimer.setInterval(() => {
      console.log("Fetching");
    }, parseInt(this.state.intervalInput, 10));

    this.setState({
      fetchInterval: timerId
    });
  }
```

As far as I can tell `const RNBackgroundTimer = NativeModules.RNBackgroundTimer;` does not work in our case. Could it be that this library is simply incompatible with `create-react-native-app` projects that have not yet [ejected](https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/README.md#ejecting-from-create-react-native-app)?

**Comment by Kuluum** [comment]
@cideM See this thread https://github.com/ocetnik/react-native-background-timer/issues/35#issuecomment-312929796

**Comment by richardbonneau** [comment]
Kuluum's link doesn't refer to the same error. Can we reopen this thread please.

**Comment by muhammadsr** [comment]
Having the same issue :(

**Comment by ocetnik** [comment]
@richardbonneau Do you use Expo? If yes then [you'll just need to](https://facebook.github.io/react-native/docs/getting-started#caveats) "[eject](https://docs.expo.io/versions/latest/expokit/eject)". Otherwise, try to link the library manually. I updated the installation section in the readme.
