### ISSUE TITLE
Not supported in RN 0.45?

### ISSUE THREAD

**Issue by DigohD** [ocetnik/react-native-background-timer#44]
When I try to install via npm I get the following answer:
UNMET PEER DEPENDENCY react-native@0.44.3

Am I maybe doing something wrong or is it simply not compatible with RN 0.45?

thanks!

**Comment by ocetnik** [comment]
Hi @DigohD,

ReactNative 0.45 is supported

react-native-background-timer has in [package.json](https://github.com/ocetnik/react-native-background-timer/blob/master/package.json#L23) peer dependency react-native >=0.40.0

When I create new project with React and ReactNative
```
npm init
npm i react@16.0.0-alpha.12 --save
npm i react-native@0.45.0 --save
```
and then I add react-native-background-timer
```
npm i react-native-background-timer --save
```  
no peer dependency warning is thrown. So problem is probably not in this library.

David
