### ISSUE TITLE
Native module cannot be null. 

### ISSUE THREAD

**Issue by jackie-ni** [ocetnik/react-native-background-timer#45]
While using react native with expo and the background timer, my phone displayed "Native module cannot be null". What does this mean and how can I fix it?

**Comment by leonardocarvalho** [comment]
Have you run `react-native link react-native-background-timer`?

**Comment by aldente05** [comment]
+1

i already do `react-native link react-native-background-timer`

"react-native-background-timer": "^1.2.0"
react-native-cli: 2.0.1
npm : 5.3.0
xcode : 8

**Comment by NonkelDaniel** [comment]
I am having the same issue, has anybody found a solution to this problem? I too have already ran the react-native link command.

**Comment by shanakaf** [comment]
Did you build the project (react-native run-ios) after installing the project? That solved  the issue for me.

**Comment by jeffreymendez1993** [comment]
you need to manually link it.  One of the files does not properly include the lib so you need to go into the node modules to link it for iOS.

**Comment by natterstefan** [comment]
@aldente05 @NonkelDaniel this should help, as it did for me: https://github.com/ocetnik/react-native-background-timer/issues/35#issuecomment-312783840

**Comment by zorobabel** [comment]
@elN1n0 I have the same issue and sadly this module won't work with Expo, you have to [detach it](https://docs.expo.io/versions/latest/guides/detach.html)

**Comment by ocetnik** [comment]
Duplicates #70 #72
