### ISSUE TITLE
Task defined did not run in IOS

### ISSUE THREAD

**Issue by CharltonC** [ocetnik/react-native-background-timer#46]
Followed installations and the example specified in "Usage". However in the React Native Debugger in Chrome, only the first message "tic" get logged when the App is active. When the app goes to background, no messages "tic" got logged. Not sure what I missed.

Xcode: 8.2.1
NPM: 3.10.10
"react": "16.0.0-alpha.12",
"react-native": "0.45.1",

**Comment by y2k-shubham** [comment]
(Almost) same as https://github.com/ocetnik/react-native-background-timer/issues/54

**Comment by ocetnik** [comment]
#66 merged and v2.0.0 released
