### ISSUE TITLE
Testing background timer with useFakeTimers in Jest

### ISSUE THREAD

**Issue by aphillipo** [ocetnik/react-native-background-timer#465]
Hello there! Thanks so much for this module it's proving invaluable for me on my current project.

I wanted to be able to do something like this:

```es6
import { Timer } from './timer';

jest.useFakeTimers();

jest.spyOn(global, 'setInterval');
jest.spyOn(global, 'clearInterval');

// replace bg timer with set interval.
jest.mock('react-native-background-timer', () => {
  return {
    setInterval: setInterval,
    clearInterval: clearInterval,
  };
});

describe('Timer', () => {
 it('should repeat a callback every X milliseconds', () => {
    const timer = new Timer();

    const interval = 1000;
    const callback = jest.fn();

    const id = timer.setInterval(callback, interval);

    jest.advanceTimersByTime(3000);

    timer.clearTimer(id);
    // timer.destroy();

    expect(callback).toHaveBeenCalledTimes(2);
  });
});
```

However `setInterval` seems to be the one from node rather than the one created by `jest.useFakeTimers()`.

How would you go about mocking BackgroundTimer.setInterval()? Actually thinking about it maybe creating a separate mock file will do the trick, let me try this and import it and see. I'll follow up here if I find a solution.

**Comment by aphillipo** [comment]
No moving the mocking of the setInterval mock to a separate file doesn't seem to work. So strange.

**Comment by aphillipo** [comment]
It was my fault, Date.now is not changed by jest.advanceTimersByTime so you need to mock this separately somehow.

**Comment by SolankiYogesh** [comment]
@aphillipo have you find any solution ? if yes then please do let me know

**Comment by SolankiYogesh** [comment]
```
jest.mock('react-native-background-timer', () => {
  return {
    setInterval,
    clearInterval
  }
})
```
