### ISSUE TITLE
Terminating app, bridge is not set.

### ISSUE THREAD

**Issue by leonardocarvalho** [ocetnik/react-native-background-timer#47]
Hi guys,

I'm having this intermittent error (50%) on ios simulator reload:

`<Error>: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'bridge is not set. This is probably because you've explicitly synthesized the bridge in RNBackgroundTimer, even though it's inherited from RCTEventEmitter.'`

Any ideas why this is happening? This is strange given the last release, where I don't see the synthesize of the bridge anymore.

**Comment by blairvanderhoof** [comment]
Same issue after upgrading react native to 0.47.1

**Comment by dnish** [comment]
Having exactly the same issue

**Comment by SudoPlz** [comment]
I'm seeing that issue as well since I upgraded to react-native 0.47.*

**Comment by NonkelDaniel** [comment]
I am also running into this bug, it is severely hindering the development process here; any news on it? Cheers

**Comment by hhff** [comment]
Same here all!

**Comment by mobinni** [comment]
Seems to be a fix in 0.49 https://github.com/facebook/react-native/commit/1f9fc0ee3a2964b067f0848e35603475e510067c

**Comment by reyalpsirc** [comment]
Just made a pull request for this that simply prevents the crash until a better solution happens on the React Native side. At least this way we can boost the development speed a bit without those crashes happening all the time.

**Comment by ocetnik** [comment]
Fixed in #61 
Thank you @reyalpsirc 
Released v1.3.0
