### ISSUE TITLE
background task dosen't work when device is in sleep mode.

### ISSUE THREAD

**Issue by Ramin-Khodaie** [ocetnik/react-native-background-timer#482]
I start a background task which is responsible to create and make a signalR connection.
the task is running well when app is in both foreground and background state, but when device goes in sleep mode the task stop from running and we lost our connection and as soon as we unlock the device(or even just open it to enter unlock code) we get the connection again.

the task just check whether there is connected signalR instance or not, if the status is disconnected, it tries to start the connection again.

here is my implementation :

export const SignalRProvider = ({children, otpObject}: any) => {
  const {appGuid, mobileNumber} = otpObject;

  const signalr = SignalR.getInstance(appGuid, mobileNumber);

  // Restart connection when it gets disconnected.

  const restartConnection = () => {
    if (signalr.connection?.state === 'Disconnected') {
      signalr.start();
    }
  };

  useEffect(() => {
    // Run signalr restartConnection method as background task

    const intervalId = backgroundTask(restartConnection);
  }, []);

  return (
    <SignalRContext.Provider value={{connection: signalr.connection}}>
      {children}
    </SignalRContext.Provider>
  );
};

and this is background task implementation : 

import BackgroundTimer from 'react-native-background-timer';

// Define the background task function
const backgroundTask = (someTask: any) => {
  // Schedule the next execution of the background task, task will be run every 30 seconds.
  const intervalId = BackgroundTimer.setInterval(() => {
    someTask();
  }, 30000);

  return intervalId;
};

export default backgroundTask;

I just pass the task to backgroundTask function and expect to be run every 3 seconds.

but as I said it dosen't work when device goes in sleep mode.

i will appreciate your suggestions in advance, thanks.

**Comment by fukemy** [comment]
can u format the code again?

**Comment by ThushalIntervest** [comment]
did you find any solution for this?

**Comment by javiermojito** [comment]
We still waiting for a solution

**Comment by Shhreyas** [comment]
still waiting..... can you please suggest any other solution?

**Comment by fukemy** [comment]
I think thats i posible, the higer Device OS vesion, less bg job we can do

**Comment by MaruanBO** [comment]
@Ramin-Khodaie Since i do not know if this happen on both OS or only in one. Let use IOS as example, generally i can tell you that’s  due the limitation on background task for ios, but you can use Background Fetch to periodically check if they are connected to the instance or not. Also do not forget if you wanna more than 30 seconds of running your task on background, request the permission of audio, bluetooth or location. Check this out: [preparing_your_ui_to_run_in_the_background/using_background_tasks_to_update_your_app](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/using_background_tasks_to_update_your_app)

**Comment by Ramin-Khodaie** [comment]
@MaruanBO I found the solution at using [react-native-background-actions](https://www.npmjs.com/package/react-native-background-actions) package.The target was android and it works, but as you said and mentioned in the document of this package,it has some limitation in dealing with jobs at background.

**Comment by rmn-kh** [comment]
@MaruanBO I found the solution at using [react-native-background-actions](https://www.npmjs.com/package/react-native-background-actions) package.The target was android and it works, but as mentioned in the document of this package,it has some limitation in dealing with jobs at background when used in iOS.
