### ISSUE TITLE
Error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by BogdanHossu** [ocetnik/react-native-background-timer#50]
When trying to run my android project, I receive the following error and the build is failing:
`/node_modules/react-native-background-timer/android/src/main/java/com/ocetnik/timer/BackgroundTimerPackage.java:26: error: method does not override or implement a method from a supertype
    @Override`

What can be one of the causes?

**Comment by BogdanHossu** [comment]
Silly me, its most probably because of this https://github.com/facebook/react-native/releases/tag/v0.47.0. Ill make a PR with the fix.

**Comment by dmitry-zaporozhan** [comment]
https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8

**Comment by ocetnik** [comment]
👍
