### ISSUE TITLE
react-native-background-timer not working in android

### ISSUE THREAD

**Issue by Qurat-ul-ainn** [ocetnik/react-native-background-timer#525]
this is my code that is totally working fine in ios and not working in android

  useEffect(() => {
        const handleAppStateChange = (nextAppState) => {
            if (nextAppState === 'background') {
                // Start the background task
                startBackgroundTask();
            } else if (nextAppState === 'active') {
                // Stop the background task
                BackgroundTimer.stopBackgroundTimer(); // Make sure this method exists in BackgroundTimer
            }
        };
    
        AppState.addEventListener('change', handleAppStateChange);
    
        return () => {
            AppState.removeEventListener('change', handleAppStateChange);
            BackgroundTimer.stopBackgroundTimer(); // Ensure the timer is stopped when the component unmounts
        };
    }, []);

    const startBackgroundTask = () => {
            BackgroundTimer.runBackgroundTimer(() => {
                // This code will run even when app is in the background
                if (timeRemaining > 0) {
                    setTimeRemaining(timeRemaining - 1);
                } else {
                    BackgroundTimer.stopBackgroundTimer(); // Stop the timer if workout is complete
                }
        }, 1000); // Execute code every 1000 ms
    };

**Comment by pencilcheck** [comment]
You need to make sure that you have a foreground service since the app will get killed and the background probably is killed as well.
