### ISSUE TITLE
Supporting multiple background timers

### ISSUE THREAD

**Issue by IjzerenHein** [ocetnik/react-native-background-timer#6]
Hi Dávid,

First of all, thanks for writing this library, awesome work! 👍 

Hey, currently it is not possible to use multiple background timers. This makes it complicated to use the library when it is used from multiple places in your app. What would you think of adding an API similar to that of `setInterval` and `setTimeout`? This would solve the problem and you could also easily replace existing setTimeout/setInterval code with `react-native-background-timer`. Like this:

```javascript
const interval = BackgroundTimer.setInterval(() => {
  console.log('this will run even if the app is in the background, woohoo :)');
}, 200);
BackgroundTimer.clearInterval(timer);

const timeout = BackgroundTimer.setTimeout(() => {
  console.log('this will run even if the app is in the background, woohoo :)');
}, 200);
BackgroundTimer.clearTimeout(timeout);
```

What do you think about this? I could add this with relative easy if you think it's good idea.

Cheers, Hein

**Comment by ocetnik** [comment]
Hi Hein,

many thanks for your pull request #5 where you also solved this problem.

Dávid

**Comment by isaaclem** [comment]
@ocetnik : on your README.md:

>  There can be used only one background timer to keep code consistent

Wondering if it's currently possible to run multiple different background-timer with different interval?

**Comment by Ajmal0197** [comment]
Can i am multiple timers in background for react Native...
In your readme it's written only timer at a moment can run...

If multiple timer exist kindly tell how to use in both platform... Thanks
