### ISSUE TITLE
installing for iOS using pod is failing with message "is a directory"

### ISSUE THREAD

**Issue by anwarhamr** [ocetnik/react-native-background-timer#62]
I'm green to iOS for sure... This was my first time adding a pod so I went to my ios folder did pod init and it created this file:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'aura_react_native' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for aura_react_native

  target 'aura_react_native-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'aura_react_nativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'aura_react_native-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for aura_react_native-tvOS

  target 'aura_react_native-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
then from my ios project folder in ran you command on the readme and get the message 'is a directory' see screen shot.  
![image](https://user-images.githubusercontent.com/525283/31245702-6e1246d8-a9c8-11e7-9793-4cd7cbf4788d.png)

**Comment by erick2014** [comment]
@anwarhamr your Podfile should be in ios directory, then run pod install within ios folder

**Comment by anwarhamr** [comment]
I've stopped using this library but will probably need it or something similar.  Closing since I'm not going to be able to validate anything in a bit.
