### ISSUE TITLE
'RCTEventEmitter.h' file not found

### ISSUE THREAD

**Issue by FrenchBully** [ocetnik/react-native-background-timer#67]
Getting this error on build 
`'RCTEventEmitter.h' file not found`

I've tried replacing with:
`'React/RCTEventEmitter.h'`

**Comment by yinghang** [comment]
Does `'React/RCTEventEmitter.h'` work for you then? In terms of the import paths, it all depends on which RN version you're running.

**Comment by FrenchBully** [comment]
I'm running RN 0.49.3, and `React/RCTEventEmitter.h` doesn't work

**Comment by yinghang** [comment]
Try `<React/RCTEventEmitter.h>`. Also, did you set up header search paths the right way?

**Comment by FrenchBully** [comment]
thanks, yea I tried `<React/RCTEventEmitter.h>` with no luck. Header Search Path set has `$(SRCROOT)/../node_modules/react-native-background-timer/ios`

**Comment by yinghang** [comment]
You'd prob want something like `$(SRCROOT)/../node_modules/react-native/` too since `RCTEventEmitter.h` would live inside the `react-native` folder. And try setting it to a recursive search.

**Comment by FrenchBully** [comment]
no luck still.

**Comment by FrenchBully** [comment]
has anyone been able to get this working?

**Comment by SprinterOPO** [comment]
Try to add below dependency to your Pods file (to the top of your target section - before `pod 'react-native-background-timer'` line):

```
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    # Add any other subspecs you want to use in your project
]
```

Then run `pod install` and see if it now works.

**Comment by kevoj** [comment]
Hi guys, this solution works!

**Add lines to  ios/Podfile**

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'
  ...

**Comment by hnliyuan** [comment]
tried replacing with:
'React/RCTEventEmitter.h'
It's works for me .
"react-native": "0.51.0",
"react-native-background-timer": "^2.0.0",

**Comment by erick2014** [comment]
I was getting a very similar error:
React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>

and I did this : https://github.com/ocetnik/react-native-background-timer/issues/78

**Comment by ocetnik** [comment]
Hi @FrenchBully @yinghang @SprinterOPO @kevoj @hnliyuan @erick2014,

could you please test it with version 2.1.0-alpha.5 and let me know if it works, please?

Thanks.
David

**Comment by pankti1210** [comment]
i am facing the same issue.. can anyone please help ?
React native version: 0.57.7
React Native Background timer: 2.0.0
COCOAPODS: 1.5.3

i tried with version React Native Background timer 2.1.1 and 2.1.0 also but getting the same issue.

**Comment by sharadkatre19** [comment]
Adding these two pods in Podfile Worked For Me.

```
pod 'React', :path => '../node_modules/react-native'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
```

Thanks.

**Comment by aangeles2807** [comment]
this worked for me!

https://github.com/microsoft/react-native-code-push/issues/1565#issuecomment-489738672

**Comment by jiteshstack** [comment]
At my end i have tried, replace `#import RCTEventEmitter.h` or `#import React/RCTEventEmitter.h` with #import `<React/RCTEventEmitter.h>`

And Its work for me
