### ISSUE TITLE
You should specify that the maximum amount of time for the timer is 3 minutes.

### ISSUE THREAD

**Issue by jeffreymendez1993** [ocetnik/react-native-background-timer#68]
This can save people time whether or not this package is a good fit for them.

**Comment by MoOx** [comment]
It's seems to be even less on recent version of iOS.

Thanks for the warning.

For more info:

- https://github.com/ocetnik/react-native-background-timer/issues/9#issuecomment-275904499
- https://github.com/ocetnik/react-native-background-timer/issues/54#issuecomment-344484898
- https://github.com/ocetnik/react-native-background-timer/issues/54#issuecomment-327985926

**Comment by isaaclem** [comment]
@jeffreymendez1993 Have you got it to run successfully in the background? I tried both way below

Method 1:
```
BackgroundTimer.start();
    this.interval = setInterval(() => {
      console.log('Testing');
    }, 1000);
```

Method 2:
```
global.backgroundTimerIntervalId = BackgroundTimer.runBackgroundTimer(() => {
      console.log(''Testing);
      }
    }, 1000);
```

Both aren't working once the app being hide in background

**Comment by jeffreymendez1993** [comment]
@isaaclem yes it is working. You config needs to be setup differently. Try the example that is on the readme it should work with that basic setup.
