### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by IronCoderXYZ** [ocetnik/react-native-background-timer#70]
Hi, first off, I have had much success with this library before, so thank you.
Currently I am receiving the error: 'Native Module cannot be null'.
If i link this module in my podfile as described, it installs react v0.11.0, which is deprecated and leads to compile errors.

Has anyone encountered this?

**Comment by cpunion** [comment]
Must run `react-native link react-native-background-timer` and then compile native.

**Comment by IronCoderXYZ** [comment]
@cpunion I still receive the same error unfortunately

**Comment by Gerharddc** [comment]
I have the same issue (on RN 0.52 if it matters)

**Comment by Gerharddc** [comment]
Ok so reinstalling the pods fixed it for me.

**Comment by maslianok** [comment]
@Gerharddc Great, works for me as well

```
cd ios && pod install
```

**Comment by ocetnik** [comment]
Duplicates #72

**Comment by ocetnik** [comment]
Duplicates #45
