### ISSUE TITLE
BackgroundTimer.stopBackgroundTimer() not stopping timer.

### ISSUE THREAD

**Issue by Saumyadip-Pramanik** [ocetnik/react-native-background-timer#81]

**Comment by Elmarino** [comment]
+1 on android, not tested on iOS

**Comment by BlowofDeath** [comment]
There is a problem, BackgroundTimer.stopBackgroundTimer() is working but only when you use it in the same block of code where Timer was started. BackgroundTimer.stopBackgroundTimer() does not work globally. Is there any fix for that?

**Comment by ocetnik** [comment]
Hi @BlowofDeath,
have you tried version `2.1.0-alpha.6`?

**Comment by BlowofDeath** [comment]
Yes, Exactly this version

**Comment by ocetnik** [comment]
@Saumyadip-Pramanik @Elmarino @BlowofDeath @wdayanand fixed in `react-native-background-timer@2.1.1`

**Comment by vrgimael** [comment]
Still having this issue on 2.1.1 and RN 0.58.5 on iOS, is there any workaround?

**Comment by namtn-0873** [comment]
@ocetnik I still got this issue on 2.1.1 and RN 0.59.3 on iOS :(

**Comment by kevtran410** [comment]
@ocetnik i still got this issue on 2.1.1 and RN 0.59.3 on iOS, can you help :(

**Comment by Bang9** [comment]
@ocetnik how to shut itself down? below code is not working
```
        BackgroundTimer.runBackgroundTimer(() => {
            console.log("hello my name is timer.. i will remove me, byebye");
            BackgroundTimer.stopBackgroundTimer();
        }, 2000);
```

**Comment by Matgsan** [comment]
> @ocetnik how to shut itself down? below code is not working
> 
> ```js
>         BackgroundTimer.runBackgroundTimer(() => {
>             console.log("hello my name is timer.. i will remove me, byebye");
>             BackgroundTimer.stopBackgroundTimer();
>         }, 2000);
> ```

Same issue, were u able to solve it?

**Comment by Bang9** [comment]
@Matgsan try below
```js
BackgroundTimer.runBackgroundTimer(() => {
    setTimeout(() => BackgroundTimer.stopBackgroundTimer() ,0);
}, 2000);
```

**Comment by Ella-noncelab** [comment]
> @Matgsan try below
> 
> ```js
> BackgroundTimer.runBackgroundTimer(() => {
>     setTimeout(() => BackgroundTimer.stopBackgroundTimer(), 0);
> }, 2000);
> ```

You save my life
