### ISSUE TITLE
fatal error: 'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by rcidt** [ocetnik/react-native-background-timer#87]
When attempting to archive the app on iOS, I get 

`RNBackgroundTimer.h:9:9: fatal error: 'React/RCTBridgeModule.h' file not found`

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

**Comment by syntheticsgr** [comment]
Same thing here!

**Comment by yeung108** [comment]
Same...

**Comment by alexkuttig** [comment]
Did you install the lib via CocoaPods? 
I got the same error when installing it via CocoaPods, but it worked fine when I added the lib to my project manually (like described here - manual linking - step 1+2 https://facebook.github.io/react-native/docs/linking-libraries-ios.html).

**Comment by konstantin-mohin** [comment]
@alexkuttig thanks,
just tried your solution and it's working
