### ISSUE TITLE
Update SDK version 23.0.1 to 26

### ISSUE THREAD

**Issue by souzamarcos** [ocetnik/react-native-background-timer#91]
Will you update the React Native Background Timer to be compatible with React Native 0.56?

I trying to run my app on android with React Rative 0.56 but I can't resolve the React Native Background Timer.
![image](https://user-images.githubusercontent.com/12562079/43370415-0fa888ce-9355-11e8-90dd-ebfcb5799b56.png)

**Comment by ocetnik** [comment]
Hi @souzamarcos,

it [was updated](https://github.com/ocetnik/react-native-background-timer/commit/f9487018f23f6f3b4e2fe8db3a0288c28664dd14).

You can try it with `yarn upgrade react-native-background-timer@2.1.0-alpha.5`

It will be released in next release.

David

**Comment by souzamarcos** [comment]
@ocetnik Thank you
