### ISSUE TITLE
TypeError:undefined is not an object(ecaluating RNBackgroundTimer.setTimeout)

### ISSUE THREAD

**Issue by sjq9026** [ocetnik/react-native-background-timer#93]
![image](https://user-images.githubusercontent.com/12949279/43578209-ab9ae5a0-9680-11e8-8597-f8f1cbb326da.png)

**Comment by paulmand3l** [comment]
Same issue.

"react": "16.3.1",
"react-native": 0.55.3"
"react-native-background-timer": "^2.0.1",

**Comment by ocetnik** [comment]
Hi @sjq9026 @paulmand3l,

please try `yarn upgrade react-native-background-timer@2.1.0-alpha.5` [it is fixed there](https://github.com/ocetnik/react-native-background-timer/commit/95122baae9d0d21764f1e4145f98ee7012ba39f5).

Thanks.
David
