### ISSUE TITLE
Timer not being terminated

### ISSUE THREAD

**Issue by gitsuraj** [ocetnik/react-native-background-timer#96]
I am taking cross platform approach to setup background timer. I have registered background timer on componentWillMount and stopped in componentWillUnmount.

Even when view is changed functions in timer is still getting called. I was planning to have some jobs for certain Component only.

BackgroundTimer.runBackgroundTimer(() => { 
//code that will be called every 3 seconds 
}, 
3000);

BackgroundTimer.stopBackgroundTimer(); //after this call all code on background stop run.

**Comment by johntitus** [comment]
Not a fix, but I ran into the same issue with the latest codebase (pulled from github, not npm). I found the following works on iOS and correctly clears the timer:

```js
const intervalId = BackgroundTimer.setInterval(() => {
    tick();
}, 1000);

BackgroundTimer.clearInterval(intervalId);
```

**Comment by ocetnik** [comment]
@gitsuraj @johntitus you can try `yarn upgrade react-native-background-timer@2.1.0-alpha.5`

**Comment by nivort** [comment]
@johntitus @ocetnik  thanks, after upgrade to 2.1.0-alpha.5 and use `BackgroundTimer.setInterval`, it works as expected.
